export const EVM_NETWORKS = [
  { id: 'eip155:1', label: 'Ethereum', chainId: 1, nativeSymbol: 'ETH' },
  { id: 'eip155:56', label: 'BNB Smart Chain', chainId: 56, nativeSymbol: 'BNB' },
  { id: 'eip155:137', label: 'Polygon', chainId: 137, nativeSymbol: 'POL' },
  { id: 'eip155:43114', label: 'Avalanche C-Chain', chainId: 43114, nativeSymbol: 'AVAX' },
  { id: 'eip155:250', label: 'Fantom Opera', chainId: 250, nativeSymbol: 'FTM' },
  { id: 'eip155:42161', label: 'Arbitrum One', chainId: 42161, nativeSymbol: 'ETH' },
  { id: 'eip155:10', label: 'Optimism', chainId: 10, nativeSymbol: 'ETH' },
  { id: 'eip155:8453', label: 'Base', chainId: 8453, nativeSymbol: 'ETH' },
  { id: 'eip155:324', label: 'zkSync Era', chainId: 324, nativeSymbol: 'ETH' },
  { id: 'eip155:59144', label: 'Linea', chainId: 59144, nativeSymbol: 'ETH' },
  { id: 'eip155:534352', label: 'Scroll', chainId: 534352, nativeSymbol: 'ETH' },
  { id: 'eip155:42220', label: 'Celo', chainId: 42220, nativeSymbol: 'CELO' },
  { id: 'eip155:1666600000', label: 'Harmony', chainId: 1666600000, nativeSymbol: 'ONE' },
  { id: 'eip155:8217', label: 'Klaytn', chainId: 8217, nativeSymbol: 'KLAY' },
  { id: 'eip155:295', label: 'Hedera', chainId: 295, nativeSymbol: 'HBAR' },
  { id: 'eip155:1284', label: 'Moonbeam', chainId: 1284, nativeSymbol: 'GLMR' },
  { id: 'eip155:592', label: 'Astar', chainId: 592, nativeSymbol: 'ASTR' },
  { id: 'eip155:25', label: 'Cronos', chainId: 25, nativeSymbol: 'CRO' },
  { id: 'eip155:66', label: 'OKX Chain', chainId: 66, nativeSymbol: 'OKT' },
  { id: 'eip155:2222', label: 'Kava EVM', chainId: 2222, nativeSymbol: 'KAVA' },
  { id: 'eip155:122', label: 'Fuse', chainId: 122, nativeSymbol: 'FUSE' },
  { id: 'eip155:1313161554', label: 'Aurora', chainId: 1313161554, nativeSymbol: 'ETH' },
  { id: 'eip155:42262', label: 'Oasis Emerald', chainId: 42262, nativeSymbol: 'ROSE' },
  { id: 'eip155:4689', label: 'IoTeX', chainId: 4689, nativeSymbol: 'IOTX' },
  { id: 'eip155:1088', label: 'Metis', chainId: 1088, nativeSymbol: 'METIS' },
  { id: 'eip155:288', label: 'Boba Network', chainId: 288, nativeSymbol: 'ETH' },
  { id: 'eip155:47805', label: 'Rei Network', chainId: 47805, nativeSymbol: 'REI' },
  { id: 'eip155:9001', label: 'Evmos', chainId: 9001, nativeSymbol: 'EVMOS' },
  { id: 'eip155:7700', label: 'Canto', chainId: 7700, nativeSymbol: 'CANTO' },
  { id: 'eip155:1074', label: 'ShimmerEVM', chainId: 1074, nativeSymbol: 'SMR' },
  { id: 'eip155:53935', label: 'DFK Chain', chainId: 53935, nativeSymbol: 'JEWEL' },
  { id: 'eip155:82', label: 'Meter', chainId: 82, nativeSymbol: 'MTR' },
  { id: 'eip155:40', label: 'Telos', chainId: 40, nativeSymbol: 'TLOS' },
  { id: 'eip155:88', label: 'Viction', chainId: 88, nativeSymbol: 'VIC' },
  { id: 'eip155:30', label: 'RSK', chainId: 30, nativeSymbol: 'RBTC' },
] as const;

export type EvmNetworkId = (typeof EVM_NETWORKS)[number]['id'];

export type NetworkCapability = 'eip681' | 'solana-native' | 'manual-native-uri' | 'no-interoperable-contract-uri';

export interface NetworkCatalogEntry {
  id: string;
  label: string;
  capability: NetworkCapability;
  note: string;
}

export const NETWORK_CATALOG: NetworkCatalogEntry[] = [
  ...EVM_NETWORKS.map((network) => ({ id: network.id, label: network.label, capability: 'eip681' as const, note: `EIP-681, chain ID ${network.chainId}` })),
  { id: 'solana', label: 'Solana', capability: 'solana-native', note: 'Generated by the native Solana transaction builder' },
  { id: 'cardano', label: 'Cardano', capability: 'manual-native-uri', note: 'Wallet-specific Cardano deep links vary; paste only a verified wallet URI' },
  { id: 'xrpl', label: 'XRPL', capability: 'manual-native-uri', note: 'Wallet-specific XRPL deeplinks vary; paste only a verified wallet URI' },
  { id: 'bitcoin', label: 'Bitcoin', capability: 'manual-native-uri', note: 'BIP-21 supports payments, not arbitrary contract calls' },
  { id: 'near', label: 'NEAR', capability: 'no-interoperable-contract-uri', note: 'No broadly interoperable native contract-call URI standard' },
  { id: 'aptos', label: 'Aptos', capability: 'no-interoperable-contract-uri', note: 'No broadly interoperable native contract-call URI standard' },
  { id: 'sui', label: 'Sui', capability: 'no-interoperable-contract-uri', note: 'No broadly interoperable native contract-call URI standard' },
  { id: 'polkadot', label: 'Polkadot', capability: 'no-interoperable-contract-uri', note: 'Wallet and parachain deep-link formats are not a universal contract-call standard' },
  { id: 'cosmos', label: 'Cosmos', capability: 'no-interoperable-contract-uri', note: 'Wallet deep links are app-specific; no universal CosmWasm URI' },
  { id: 'icp', label: 'Internet Computer', capability: 'no-interoperable-contract-uri', note: 'No broadly interoperable native contract-call URI standard' },
  { id: 'multiversx', label: 'MultiversX', capability: 'no-interoperable-contract-uri', note: 'No broadly interoperable native contract-call URI standard' },
  { id: 'algorand', label: 'Algorand', capability: 'no-interoperable-contract-uri', note: 'No broadly interoperable native contract-call URI standard' },
  { id: 'tezos', label: 'Tezos', capability: 'no-interoperable-contract-uri', note: 'Wallet deep links are app-specific; no universal contract-call URI' },
  { id: 'neo', label: 'NEO N3', capability: 'no-interoperable-contract-uri', note: 'No broadly interoperable native contract-call URI standard' },
  { id: 'waves', label: 'Waves', capability: 'no-interoperable-contract-uri', note: 'No broadly interoperable native contract-call URI standard' },
  { id: 'zilliqa', label: 'Zilliqa', capability: 'no-interoperable-contract-uri', note: 'No broadly interoperable native contract-call URI standard' },
  { id: 'flow', label: 'Flow', capability: 'no-interoperable-contract-uri', note: 'No broadly interoperable native contract-call URI standard' },
  { id: 'kadena', label: 'Kadena', capability: 'no-interoperable-contract-uri', note: 'No broadly interoperable native contract-call URI standard' },
  { id: 'ton', label: 'TON', capability: 'no-interoperable-contract-uri', note: 'No broadly interoperable native contract-call URI standard' },
  { id: 'thorchain', label: 'THORChain', capability: 'no-interoperable-contract-uri', note: 'No broadly interoperable native contract-call URI standard' },
  { id: 'stacks', label: 'Stacks', capability: 'no-interoperable-contract-uri', note: 'No broadly interoperable native contract-call URI standard' },
  { id: 'citrea', label: 'Citrea', capability: 'no-interoperable-contract-uri', note: 'No established public wallet URI standard' },
  { id: 'bob', label: 'BOB', capability: 'no-interoperable-contract-uri', note: 'No established public wallet URI standard' },
  { id: 'litvm', label: 'LitecoinVM', capability: 'no-interoperable-contract-uri', note: 'No established public wallet URI standard' },
  { id: 'fabric', label: 'Hyperledger Fabric', capability: 'no-interoperable-contract-uri', note: 'Enterprise permissioned network; no public wallet QR standard' },
];

export interface Eip681Request {
  chainId: number;
  recipient: string;
  valueWei?: bigint;
  contractAddress?: string;
  functionName?: string;
  parameters?: Record<string, string>;
}

export interface Eip5792Call {
  to: string;
  data?: string;
  value?: string;
}

export interface Eip5792Request {
  version: '1.0';
  chainId: string;
  from: string;
  atomicRequired: boolean;
  calls: Eip5792Call[];
}

export interface Erc7715PermissionRequest {
  chainId: number;
  contract: string;
  function: string;
  args: string[];
  permissions: { type: 'recurring-transfer'; maxAmount: string; periodSeconds: number }[];
}

export interface CosmosMessage {
  typeUrl: string;
  value: Record<string, unknown>;
}

export interface MoveCall {
  module: string;
  function: string;
  arguments: string[];
}

export interface ManifestAction {
  chain: string;
  uri: string;
  label: string;
  summary: string;
  permissionRequest?: Erc7715PermissionRequest;
  walletRequest?: Eip5792Request;
}

export interface ActionManifest {
  version: 1;
  expiresAt: string;
  actions: ManifestAction[];
}

function assertEvmAddress(address: string, field: string): string {
  const normalized = address.trim();
  if (!/^0x[0-9a-fA-F]{40}$/.test(normalized)) {
    throw new Error(`${field} must be a 20-byte EVM address`);
  }
  return normalized;
}

/** Builds the JSON-RPC params for wallet_sendCalls; a wallet must submit it. */
export function buildEip5792Request(
  chainId: number,
  from: string,
  calls: Eip5792Call[],
): Eip5792Request {
  if (!Number.isSafeInteger(chainId) || chainId <= 0) throw new Error('chainId must be a positive integer');
  if (calls.length === 0) throw new Error('At least one EIP-5792 call is required');
  return {
    version: '1.0',
    chainId: `0x${chainId.toString(16)}`,
    from: assertEvmAddress(from, 'From'),
    atomicRequired: true,
    calls: calls.map((call) => ({
      to: assertEvmAddress(call.to, 'Call target'),
      ...(call.data === undefined ? {} : { data: call.data }),
      ...(call.value === undefined ? {} : { value: call.value }),
    })),
  };
}

export function buildErc7715PermissionRequest(
  chainId: number,
  contract: string,
  functionName: string,
  args: string[],
  maxAmount: string,
  periodSeconds: number,
): Erc7715PermissionRequest {
  if (!Number.isSafeInteger(periodSeconds) || periodSeconds <= 0) throw new Error('Permission period must be positive');
  if (!maxAmount || BigInt(maxAmount) < 0n) throw new Error('Permission amount must be non-negative');
  return { chainId, contract: assertEvmAddress(contract, 'Permission contract'), function: functionName.trim(), args, permissions: [{ type: 'recurring-transfer', maxAmount, periodSeconds }] };
}

export function buildCosmosBatchUri(chain: string, messages: CosmosMessage[]): string {
  if (!chain.trim() || messages.length === 0) throw new Error('Cosmos batch requires a chain and message');
  return `cosmos:${encodeURIComponent(chain)}?msgs=${encodeURIComponent(JSON.stringify(messages))}`;
}

export function buildMoveBatchUri(network: 'aptos' | 'sui', calls: MoveCall[]): string {
  if (calls.length === 0) throw new Error('Move batch requires at least one call');
  return `${network}:${btoa(JSON.stringify({ version: 1, calls }))}`;
}

function queryString(parameters: Record<string, string>): string {
  const entries = Object.entries(parameters).filter(([, value]) => value.length > 0);
  return entries.length > 0
    ? `?${entries.map(([key, value]) => `${encodeURIComponent(key)}=${encodeURIComponent(value)}`).join('&')}`
    : '';
}

/** Produces an EIP-681 URI. Wallets still validate and request a separate signature. */
export function buildEip681Uri(request: Eip681Request): string {
  if (!Number.isSafeInteger(request.chainId) || request.chainId <= 0) {
    throw new Error('chainId must be a positive integer');
  }
  const recipient = assertEvmAddress(request.recipient, 'Recipient');
  if (request.valueWei !== undefined && request.valueWei < 0n) {
    throw new Error('Value cannot be negative');
  }

  if (!request.contractAddress) {
    return `ethereum:${recipient}@${request.chainId}${queryString(
      request.valueWei === undefined ? {} : { value: request.valueWei.toString() },
    )}`;
  }

  const contract = assertEvmAddress(request.contractAddress, 'Contract address');
  if (!request.functionName?.trim()) throw new Error('Contract calls require a function name');
  return `ethereum:${contract}@${request.chainId}/${encodeURIComponent(request.functionName.trim())}${queryString({
    ...(request.parameters ?? {}),
    ...(request.valueWei === undefined ? {} : { value: request.valueWei.toString() }),
  })}`;
}

/**
 * `superqr:` is an app-level manifest envelope, not a wallet transaction URI.
 * It intentionally requires the scanner to display and approve each action.
 */
export function encodeManifest(manifest: ActionManifest): string {
  if (manifest.version !== 1) throw new Error('Unsupported manifest version');
  if (!Number.isFinite(Date.parse(manifest.expiresAt))) throw new Error('expiresAt must be ISO-8601');
  if (manifest.actions.length === 0) throw new Error('At least one action is required');
  const encoded = new TextEncoder().encode(JSON.stringify(manifest));
  let binary = '';
  encoded.forEach((byte) => { binary += String.fromCharCode(byte); });
  return `superqr:${btoa(binary)}`;
}

export function decodeManifest(uri: string): ActionManifest {
  if (!uri.startsWith('superqr:')) throw new Error('Not a Super QR manifest');
  const binary = atob(uri.slice('superqr:'.length));
  const bytes = Uint8Array.from(binary, (character) => character.charCodeAt(0));
  const manifest = JSON.parse(new TextDecoder().decode(bytes)) as ActionManifest;
  if (manifest.version !== 1 || !Array.isArray(manifest.actions)) throw new Error('Invalid manifest');
  return manifest;
}